version: 2.1
orbs:
  ruby: circleci/ruby@0.2.1 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-buster
        environment:
          BUNDLER_VERSION: 2.0.1
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run Sorbet
          command: srb tc
      - run:
          name: Run Tests
          command: bundle exec rake test
