#!/usr/bin/env ruby
require 'json'
require 'pry'
require "bundler/setup"
require 'sorbet_auto_typer'
require 'parser'
require 'parser/current'

Bundler.require(:default) # Load up everything where this file is being run.

if ARGV.size < 1
  puts "Usage: bundle exec sorbet-auto-typer [trace_file]"
  puts
  puts "Error: not enough arguments"
  Kernel.exit(1)
end

trace_file = ARGV.first
uniq_trace_lines = Set.new()

File.foreach(trace_file) do |line|
  uniq_trace_lines << line
end

traces = uniq_trace_lines.map do |l|
  SorbetAutoTyper::MethodTrace.from_trace_line(l.strip)
end

annotator = SorbetAutoTyper::Annotator.new(traces)

all_files = traces.map(&:method_file).uniq
all_files.each do |source_file|
  puts "---------------------------------------------------"
  puts source_file
  puts "---------------------------------------------------"
  puts annotator.annotate_file(source_file)
  puts
  puts
end
